version: "3"
services:
  frontend:
    image: yanggwangseong/housework-frontend:latest
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
  
  nginx:
    restart: always
    image: yanggwangseong/housework-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  
  backend:
    image: yanggwangseong/housework-backend:latest
    container_name: app_backend
    command: npm run start:dev
    volumes:
      # - /app/node_modules
      - ./backend:/app
    environment:
      POSTGRESQL_HOST: $POSTGRESQL_ROOT_PASSWORD
      POSTGRESQL_USER: $POSTGRESQL_USER
      POSTGRESQL_ROOT_PASSWORD: $POSTGRESQL_ROOT_PASSWORD
      POSTGRESQL_DATABASE: $POSTGRESQL_DATABASE
      POSTGRESQL_PORT: $POSTGRESQL_PORT
    