version: "3"
services:
  frontend:
    image: yanggwangseong/housework-frontend:latest
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
  
  nginx:
    restart: always
    image: yanggwangseong/housework-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
  
  backend:
    image: yanggwangseong/housework-backend:latest
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m