version: "3"
services:
  frontend:
    image: yanggwangseong/housework-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
  
  nginx:
    restart: always
    image: yanggwangseong/housework-nginx
    ports:
      - "80:80"
  
  backend:
    image: yanggwangseong/housework-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m